version: "3"
services:
  reverseproxy:
    image: bravytech/reverseproxy:v2022_1
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - backend-user
      - backend-feed
    # networks:
    #   - frontend
    #   - backend
  backend-user:
    image: bravytech/udagram-api-user:v2022_1
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DATABASE: $POSTGRES_DATABASE
      POSTGRES_HOST: $POSTGRES_HOST
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE
      AWS_S3_BUCKET: $AWS_S3_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"
  backend-feed:
    image: bravytech/udagram-api-feed:v2022_1
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DATABASE: $POSTGRES_DATABASE
      POSTGRES_HOST: $POSTGRES_HOST
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE
      AWS_S3_BUCKET: $AWS_S3_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"
  frontend:
    image: bravytech/udagram-frontend:v2022_1
    ports:
      - "8100:80"

# networks:
#   frontend:
#   backend: